version: "3"

services:
  node-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes:
      - ..:/workspace
    working_dir: /workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
  dbui:
    image: adminer
    ports:
      - 3003:8080

volumes:
  postgres-data:
